---
title: "DSextra3"
author: "Hening CUi"
date: "12/3/2021"
output: github_document
---

```{r,echo = FALSE}
library (tidyverse)
library(glmnet)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

knitr::opts_chunk$set(
  fig.width = 8,
  fig.height =6,
  out.width = "90%"
)

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lasso

prediction birthweight
```{r}
bwt_df = 
  read_csv("birthweight.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")) %>% 
  sample_n(200)
```

do lasso

```{r}
y = bwt_df %>% pull(bwt)
x = model.matrix(bwt ~., bwt_df)[, -1]
```

```{r}
lambda_grid = 10 ^ seq(3, -2, by = -0.1)
lasso_fit = glmnet(x, y, lambda = lambda_grid)
lasso_cv = cv.glmnet(x, y, lambda = lambda_grid)
lambda_opt = lasso_cv$lambda.min
```

```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>% 
  filter(term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda), y = estimate, group = term, color = term)) +
  geom_path()
```

## cluster pokeman

```{r}
pokemon_df =
  read_csv("pokemon.csv") %>% 
  janitor::clean_names() %>% 
  select(speed, hp)
```

quick look

```{r}
pokemon_df %>% 
  ggplot(aes(x = hp, y = speed)) + geom_point()
```

K-means to identify cluster

```{r}
kmeans_fit =
  kmeans(x = pokemon_df, centers = 3)
```


```{r}
pokemon_df %>% 
  broom::augment(kmeans_fit, .) %>% 
  ggplot(aes(x = hp, y = speed, color = .cluster)) + 
  geom_point()
```

```{r}
clusts =
  tibble(k = 2:4) %>%
  mutate(
    km_fit =    map(k, ~kmeans(pokemon_df, .x)),
    augmented = map(km_fit, ~broom::augment(.x, pokemon_df))
  )

clusts %>% 
  select(-km_fit) %>% 
  unnest(augmented) %>% 
  ggplot(aes(hp, speed, color = .cluster)) +
  geom_point(aes(color = .cluster)) +
  facet_grid(~k)
```

## cluster intercept  and slope

```{r}
traj_data = 
  read_csv("trajectories.csv")
```

```{r}
traj_data %>% 
  ggplot(aes(x = week, y = value, group = subj)) + 
  geom_point() + 
  geom_path()
```

```{r}
int_slope_df = 
  traj_data %>% 
  nest(data = week:value) %>% 
  mutate(
    models = map(data, ~lm(value ~ week, data = .x)),
    result = map(models, broom::tidy)
  ) %>% 
  select(subj, result) %>% 
  unnest(result) %>% 
  select(subj, term, estimate) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  rename(int = "(Intercept)", slope = week)
```

```{r}
int_slope_df %>% 
  ggplot(aes(x = int, y = slope)) + 
  geom_point()
```

```{r}
km_fit = 
  kmeans(
    x = int_slope_df %>% select(-subj) %>% scale, 
    centers = 2)

int_slope_df =
  broom::augment(km_fit, int_slope_df)
```

```{r}
int_slope_df %>% 
  ggplot(aes(x = int, y = slope, color = .cluster)) +
  geom_point()
```
```{r}
left_join(traj_data, int_slope_df) %>% 
  ggplot(aes(x = week, y = value, group = subj, color = .cluster)) + 
  geom_point() + 
  geom_path() 
```

